# GitHub Actions Workflow to Build and Deploy Node.js App to Azure Web App

name: Build and deploy Node.js app to Azure Web App - Health-Insurance-Risk-Calc

on:
  push:
    branches:
      - Irving  # Change to 'main' or 'master' if necessary
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Switch to Ubuntu to avoid permission issues

    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Adjust to your preferred Node.js version

      # Step 3: Install dependencies and build the app
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build --if-present

      # Step 4: Test the app (if tests are defined)
      - name: Run Tests
        run: npm test --if-present

      # Step 5: Package the app into a zip file for deployment
      - name: Zip Files for Deployment
        run: zip -r release.zip ./*

      # Step 6: Upload the artifact for the deployment job
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for JWT-based authentication

    steps:
      # Step 1: Download the artifact from the build job
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Step 2: Unzip the artifact
      - name: Unzip Artifact
        run: unzip release.zip

      # Step 3: Log in to Azure using Service Principal credentials
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1854AD70E83D4F60B7435801109166EA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_22027BC4EE484E299E189CD7D203EAE8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E79CBFB849644C288AB88F0D33805F82 }}

      # Step 4: Deploy the app to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Health-Insurance-Risk-Calc'  # Ensure this matches your Azure Web App name
          slot-name: 'Production'
          package: .

