name: Build and deploy Node.js app to Azure Web App - Health-Insurance-Risk-Calc

on:
  push:
    branches:
      - Irving  # Adjust the branch if necessary
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Increase memory limit and install dependencies
      - name: Install Dependencies and Build
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npm install
          npm run build --if-present

      # Test the app (optional)
      - name: Run Tests
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npm test --if-present

      # Zip the files for deployment
      - name: Zip Files for Deployment
        run: zip -r release.zip ./*

      # Upload the artifact for the deploy job
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip Artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1854AD70E83D4F60B7435801109166EA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_22027BC4EE484E299E189CD7D203EAE8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E79CBFB849644C288AB88F0D33805F82 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Health-Insurance-Risk-Calc'
          slot-name: 'Production'
          package: .

